name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Check Python syntax
        run: |
          python -m compileall .

      - name: Build Docker image
        run: docker build -t uneti-vcaption .

      - name: Run Docker container (test)
        run: |
          docker run -d -p 8501:8501 --name test_app uneti-vcaption
          sleep 20
          docker logs test_app
          docker stop test_app

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'uneti-vcaption'
